name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - push_*
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker image tag
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VERSION=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ refs/heads/push_.* ]]; then
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/push_||')
            echo "VERSION=dev_${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: gamerbeaker/splinterlands-validator-swagger:${{ env.VERSION }}

      - name: Display pushed image tag
        run: |
          echo Pushed image with tag: ${{ env.VERSION }} 
